stage: dev

network: main

domain: dev.cf-metadataserver-1.eu-central-1.metadata.testing.cf-deployments.org

cf-token-metadata-registry:
  enabled: true
  values:
    api:
      image:
        tag: "0.0.1"
      tokenMetadataUpdateJob:
        enabled: false
    job:
      enabled: true
      image:
        tag: "0.0.1"
