stage: pro

network: main

domain: pro.cf-token-registry-mainnet.eu-central-1.pro.cf-token-metadata-registry.cf-deployments.org

cf-token-metadata-registry:
  enabled: true
  values:
    rwReplicaCount: 1 # rw 0 or 1
    roReplicaCount: 2
    api:
      image:
        tag: "1.3.1"
      tokenMetadataUpdateJob:
        enabled: false
    job:
      enabled: true
      image:
        tag: "1.3.1"
    ingress:
      additionalDomains:
        - tokens.cardano.org

cf-eks-monitoring:
  enabled: true
  git:
    targetRevision: "70178e2"
  alloy:
    enabled: true

prometheusStack:
  enabled: false
