stage: pro

network: preprod

domain: pro.cf-token-registry-preprod.eu-central-1.pro.cf-token-metadata-registry.cf-deployments.org

cf-token-metadata-registry:
  enabled: true
  values:
    rwReplicaCount: 1 # rw 0 or 1
    roReplicaCount: 2
    api:
      image:
        tag: "1.3.1"
      tokenMetadataUpdateJob:
        enabled: false
    job:
      enabled: true
      image:
        tag: "1.3.1"
    postgres:
      numberOfInstances: 1
    ingress:
      additionalDomains:
        - preprod.tokens.cardano.org
    cardano:
      node:
        host: preprod-node.play.dev.cardano.org
        port: 3001
        protocolMagic: "1"
        syncStartSlot: "0"
        syncStartBlockhash: ""
        blocksEpochCalculationInterval: "14400"
    github:
      organization: "input-output-hk"
      projectName: "metadata-registry-testnet"
      mappingsFolder: "registry"
      tmpFolder: "/tmp"
      forceClone: "false"

cf-eks-monitoring:
  enabled: true
  git:
    targetRevision: "70178e2"
  alloy:
    enabled: true
