stage: pro

network: main

domain: pro.cf-token-registry-mainnet.eu-central-1.pro.cf-token-metadata-registry.cf-deployments.org

cf-token-metadata-registry:
  enabled: true
  values:
    replicaCount: 3
    api:
      image:
        tag: "1.1.0"
      tokenMetadataUpdateJob:
        enabled: false
    job:
      enabled: true
      image:
        tag: "1.1.0"
    ingress:
      additionalDomains:
        - tokens.cardano.org
