git:
  targetRevision: null

# stage: one of [dev, uat, prod]
stage: null

# network: one of [mainnet, preprod, preview]
network: null

# domain: something like "grafana.dev.ggargiulo-clusters.eu-west-1.metadata.dev.cf-deployments.org"
domain: null

not-found:
  enabled: true

pg-pool-ii:
  enabled: false

grafana-dashboards:
  enabled: true

cf-token-metadata-registry:
  enabled: true

cf-eks-monitoring:
  enabled: false

spec:
  destination:
    server: https://kubernetes.default.svc
