replicaCount: 1

api:
  image:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-token-metadata-registry-api
    tag: "0.0.1"
    pullPolicy: Always

job:
  image:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-token-metadata-registry-job
    tag: "0.0.1"
    pullPolicy: Always
  cron: "15 * * * *"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9093

ingress:
  enabled: true
  disableActuatorEndpoint: true
  additionalDomains: []

postgres:
  host: cf-token-metadata-registry-pg
  port: 5432
  dbName: cf_token_metadata_registry
  schema: public
  secret:
    name: cardano.cf-token-metadata-registry-pg.credentials.postgresql.acid.zalan.do
    userKey: username
    hostKey: password


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoring:
  enabled: false
