replicaCount: 1

api:
  image:
    repository: cardanofoundation/cf-token-metadata-registry-api
    tag: "0.0.1"
    pullPolicy: Always
  tokenMetadataUpdateJob:
    enabled: true


job:
  enabled: false
  image:
    repository: cardanofoundation/cf-token-metadata-registry-job
    tag: "0.0.1"
    pullPolicy: Always
  cron: "15 * * * *"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  disableActuatorEndpoint: true
  additionalDomains: []

postgres:
  createDb: true
  numberOfInstances: 2
  host: cf-token-metadata-registry-pg
  port: 5432
  dbName: cf_token_metadata_registry
  schema: public
  secret:
    name: cardano.cf-token-metadata-registry-pg.credentials.postgresql.acid.zalan.do
    userKey: username
    hostKey: password


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoring:
  enabled: true

cardano:
  node:
    host: backbone.cardano.iog.io
    port: 3001
    protocolMagic: 764824073
