{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cf-token-metadata-registry.fullname" . }}
  labels:
    release: cf-eks-monitoring
    {{- include "cf-token-metadata-registry.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /actuator/prometheus
      port: http
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "cf-token-metadata-registry.labels" . | nindent 6 }}
{{ end }}
