name: Develop branch

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml --batch-mode --update-snapshots clean package --file ./pom.xml -DskipTests
        env:
          GH_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

      - name: Debug
        run: |
          ls -la
          printenv

      - name: Test
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml --batch-mode --update-snapshots clean verify --file ./pom.xml
        env:
          GH_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA233ZQYOM2GCW66G4
          aws-secret-access-key: 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
          aws-region: eu-west-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 747042292633.dkr.ecr.eu-west-1.amazonaws.com
          cd ./api
          docker build -t dev-cf-metadata-tools-server .
          docker tag dev-cf-metadata-tools-server:latest 747042292633.dkr.ecr.eu-west-1.amazonaws.com/dev-cf-metadata-tools-server:latest
          docker push 747042292633.dkr.ecr.eu-west-1.amazonaws.com/dev-cf-metadata-tools-server:latest

      - name: Test
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml --batch-mode --update-snapshots clean verify --file ./pom.xml
        env:
          GH_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

      - name: Deploy
        run: |
          aws ecs update-service --force-new-deployment --cluster "dev-cf-metadata-tools" --service "dev-cf-metadata-tools-server"
