name: Staging branch

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: |
          export GH_PACKAGES_USER_NAME=${{ secrets.GH_PACKAGES_USER_NAME }}
          export GH_PACKAGES_ACCESS_TOKEN=${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}
          mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml --batch-mode --update-snapshots clean package --file ./pom.xml -DskipTests
        env:
          GH_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

      - name: Test
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml --batch-mode --update-snapshots clean verify --file ./pom.xml

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        env:
          GH_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}
          ENV: staging
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 747042292633.dkr.ecr.eu-west-1.amazonaws.com
          cd ./api
          docker build \
            --build-arg GH_PACKAGES_USER_NAME=$GH_PACKAGES_USER_NAME \
            --build-arg GH_PACKAGES_ACCESS_TOKEN=$GH_PACKAGES_ACCESS_TOKEN \
            -t "${ENV}-cf-metadata-tools-server" .
          docker tag "${ENV}-cf-metadata-tools-server:latest" \
            "747042292633.dkr.ecr.eu-west-1.amazonaws.com/${ENV}-cf-metadata-tools-server:latest"
          docker push "747042292633.dkr.ecr.eu-west-1.amazonaws.com/${ENV}-cf-metadata-tools-server:latest"

      - name: Deploy
        run: |
          aws ecs update-service --force-new-deployment --cluster "${ENV}-cf-metadata-tools" --service "${ENV}-cf-metadata-tools-server"
